notifications:
  email: false
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r ./etc/requirements.txt
  - pip install psycopg2 ppygis   # workaround for unmaintained flooding code
## command to run tests
# The "flooding stuff" will break so for now just cd in ./src/test 
# and run the local tests
script: cd ./src/test && python -munittest local_usecase
